### ISSUE TITLE
e2e tests and test infrastructure for mahakam server cluster creation

### ISSUE THREAD

**Issue by vjdhama** [mahakamcloud/mahakam#65]
For checking if full cluster creation workflow is working, we need to setup e2e tests with infrastructure supporting it.

Need to brainstorm how to do it though.

Things to think about:

1. How and where to run tests.
2. How to do IP allocation(public ones) for network gateway.

**Comment by girikuncoro** [comment]
Evaluate concourse vs drone with scope/constraints:
* CI infra must be presented in DC private network (not exposed publicly) but can reach Internet
* CI infra should be pull based (because it's in private network)

Workflow that we should test:
* Git clone mahakamcloud -> run unit tests
* [e2e test] Validate mahakam server can provision cluster 
* [e2e test] Validate provisioned VMs when create cluster
